### ISSUE TITLE
Video-recorder refactor

### ISSUE THREAD

**Issue by dinzone** [linnovate/replay-infra#7]
1. Change to Path functions.
2. Extract converting routine to a new Job in RabbitMQ.

**Comment by dinzone** [comment]
3. kill the ffmpeg process with 'SIGQUIT' and not 'SIGKILL'.
4. make the fileWatcher watch on two file at the times and alert when the two of them are not getting bigger / make the main routing work with two fileWatchers and manage them.
5. Relate to metadata more importance.

**Comment by kaplanlior** [comment]
Check that using SIGQUIT doesn't produce a core dump (might start to accumulate of file system till it's full).

**Comment by dinzone** [comment]
4. console log all the process environment when the process start.
